### ISSUE TITLE
NConfig breaks with System.Web update on Windows 8.1

### ISSUE THREAD

**Issue by michielpost** [Yegoroff/NConfig#13]
Yesterday there was an update on Windows 8.1 which modified the System.Web dll.
There was a change in private fields System.Web.Caching.CacheMultiple
It used to have a private field "_caches" and now it has a private field "_cachesRefs" 

NConfig crashes with a null reference exception.
ReflectionAccessorcs line 113

Check NWebSystemConfigurator.UpdateCacheMultiple
line 57 where it gets the value of the _caches field.

Pretty scary stuff that a Windows update can break our apps. What happens when this update is applied to the Windows Azure servers? Our apps might break big time.
NConfig should not reply on these private fields, but I guess it's needed somehow to work.

**Comment by mlocke5324** [comment]
Seeing the same in our deployed production applications.  They all die on startup when they hit NConfigurator.UsingFile(...) call.  Problem started last night after automatic Windows updates.

**Comment by Yegoroff** [comment]
fixed in v 1.1.20

**Comment by michaelaird** [comment]
For others who may arrive here, I believe this is related to this KB https://support.microsoft.com/en-ca/kb/3141780

Which was delivered in cumulative updates on all versions of windows above Vista

**Comment by michaelaird** [comment]
Also, this seems to have rolled out to Server 2016. If you haven't upgraded to v1.1.22+ your applications will be down
